import string
from fuzzingbook.Grammars import srange, Grammar

#job Grammar(after normalization and multiplication to remove negative and float values)
JOB: Grammar = {
    "<start>": ["<city_development_index> <relevent_experience> <experience> <last_new_job> <training_hours> <gender_Female> <gender_Male> <gender_Other> <gender_unknown> <enrolled_university_Full_time_course> <enrolled_university_Part_time_course> <enrolled_university_no_enrollment> <enrolled_university_unknown> <education_level_Graduate> <education_level_High_School> <education_level_Masters> <education_level_Phd> <education_level_Primary_School> <education_level_unknown> <major_discipline_Arts> <major_discipline_Business_Degree> <major_discipline_Humanities> <major_discipline_No_Major> <major_discipline_Other> <major_discipline_STEM> <major_discipline_unknown> <company_size_10000> <company_size_1000_4999> <company_size_100_499> <company_size_10_49> <company_size_1_9> <company_size_5000_9999> <company_size_500_999> <company_size_50_99> <company_size_unknown> <company_type_Early_Stage_Startup> <company_type_Funded_Startup> <company_type_NGO> <company_type_Other> <company_type_Public_Sector> <company_type_Pvt_Ltd> <company_type_unknown>"],
    "<city_development_index>": ["0", "<onenine><maybe_digits>"],
    "<relevent_experience>": ["0", "<onenine><maybe_digits>"],
    "<experience>": ["0", "<onenine><maybe_digits>"],
    "<last_new_job>": ["0", "<onenine><maybe_digits>"],
    "<training_hours>": ["0", "<onenine><maybe_digits>"],
    "<gender_Female>": ["0", "<onenine><maybe_digits>"],
    "<gender_Male>": ["0", "<onenine><maybe_digits>"],
    "<gender_Other>": ["0", "<onenine><maybe_digits>"],
    "<gender_unknown>": ["0", "<onenine><maybe_digits>"],
    "<enrolled_university_Full_time_course>": ["0", "<onenine><maybe_digits>"],
    "<enrolled_university_Part_time_course>": ["0", "<onenine><maybe_digits>"],
    "<enrolled_university_no_enrollment>": ["0", "<onenine><maybe_digits>"],
    "<enrolled_university_unknown>": ["0", "<onenine><maybe_digits>"],
    "<education_level_Graduate>": ["0", "<onenine><maybe_digits>"],
    "<education_level_High_School>": ["0", "<onenine><maybe_digits>"],
    "<education_level_Masters>": ["0", "<onenine><maybe_digits>"],
    "<education_level_Phd>": ["0", "<onenine><maybe_digits>"],
    "<education_level_Primary_School>": ["0", "<onenine><maybe_digits>"],
    "<education_level_unknown>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_Arts>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_Business_Degree>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_Humanities>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_No_Major>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_Other>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_STEM>": ["0", "<onenine><maybe_digits>"],
    "<major_discipline_unknown>": ["0", "<onenine><maybe_digits>"],
    "<company_size_10000>": ["0", "<onenine><maybe_digits>"],
    "<company_size_1000_4999>": ["0", "<onenine><maybe_digits>"],
    "<company_size_100_499>": ["0", "<onenine><maybe_digits>"],
    "<company_size_10_49>": ["0", "<onenine><maybe_digits>"],
    "<company_size_1_9>": ["0", "<onenine><maybe_digits>"],
    "<company_size_5000_9999>": ["0", "<onenine><maybe_digits>"],
    "<company_size_500_999>": ["0", "<onenine><maybe_digits>"],
    "<company_size_50_99>": ["0", "<onenine><maybe_digits>"],
    "<company_size_unknown>": ["0", "<onenine><maybe_digits>"],
    "<company_type_Early_Stage_Startup>": ["0", "<onenine><maybe_digits>"],
    "<company_type_Funded_Startup>": ["0", "<onenine><maybe_digits>"],
    "<company_type_NGO>": ["0", "<onenine><maybe_digits>"],
    "<company_type_Other>": ["0", "<onenine><maybe_digits>"],
    "<company_type_Public_Sector>": ["0", "<onenine><maybe_digits>"],
    "<company_type_Pvt_Ltd>": ["0", "<onenine><maybe_digits>"],
    "<company_type_unknown>": ["0", "<onenine><maybe_digits>"],
    "<onenine>": srange("123456789"),
    "<maybe_digits>": ["", "<digits>"],
    "<digits>": ["<digit>", "<digit><digits>"],
    "<digit>": list(string.digits)
}
